#!/bin/bash

set -eu

docker_run() {
    local CERTDIR="/etc/letsencrypt"
    docker run --rm -v "$CERTDIR:$CERTDIR" xenolf/lego --path "$CERTDIR" "$@"
}

lego_commands() {
    docker_run help \
        | sed -n '/COMMANDS:/,/^$/p' \
        | sed -e '/^$/d' \
        | sed -e '/COMMANDS:/d' \
        | sed -e 's/^ \+//'
}

lego_usage() {
    docker_run -v
    echo ''
    echo '[Commands]'
    lego_commands | sed -e 's/^/    /'
    echo ''
    echo '[Additional Commands]'
    echo '    update   Update docker image'
    echo ''
    echo '[Certificates]'
    docker_run list | sed -e 's/^/    /'
}

# if docker has not installed
if [ "$(which docker)" = "" ]; then
    echo "Error: docker not exists..." >&2
    exit 1
fi

# Print version and certificates
if [ "$#" = 0 ]; then
    lego_usage
    exit
fi

# Update docker images
if [ "$1" = "update" ]; then
    echo "[ Update lego... ]"
    docker pull xenolf/lego
    exit
fi

# else if
docker_run "$@"
