#!/bin/bash

set -eu

docker_run() {
    local CERTDIR="/etc/letsencrypt"
    docker run --rm -v "$CERTDIR:$CERTDIR" xenolf/lego --path "$CERTDIR" "$@"
}

section() {
    echo ""
    echo "[""$*""]"
}

indent() {
    echo "$*" | sed -e 's/^/    /'
}

lego_commands() {
    docker_run help \
        | sed -n '/COMMANDS:/,/^$/p' \
        | sed -e '/^$/d' \
        | sed -e '/COMMANDS:/d' \
        | sed -e 's/^ \+//'
}

lego_usage() {
    # Print version
    docker_run -v

    # Print default commands
    section 'Commands'
    indent  "$(lego_commands)"

    # Print additional commands
    section 'Additional Commands'
    echo    '    update   Update docker image'

    # Print certificates
    section 'Certificates'
    indent  "$(docker_run list)"
}

# if docker has not installed
if [ "$(which docker)" = "" ]; then
    echo "Error: docker not exists..." >&2
    exit 1
fi

# Print usage if no args
if [ "$#" = 0 ]; then
    lego_usage
    exit
fi

# `lego update`
if [ "$1" = "update" ]; then
    echo "[ Update lego... ]"
    docker pull xenolf/lego
    exit
fi

# else if
docker_run "$@"
